### ISSUE TITLE
 Tab completion cuts hyphenated tags

### ISSUE THREAD

**Issue by lauft** [pfmephisto/timew-fishcompletion#2]
@pfmephisto Could you have a look at this issue here?  👉🏻 https://github.com/GothenburgBitFactory/timewarrior/issues/575

> When there are hyphenated tags, the tab completion only completes to the first hyphen, and the rest of the tag is missing.
> 
> Demonstration:
> ```txt
> [09:55:42] ❯ timew start main-unit
> Note: '"main-unit"' is a new tag.
> Tracking "main-unit"
>   Started 2023-12-12T09:55:42
>   Current                  42
>   Total               0:00:00
> [09:55:45] ❯ timew stop
> Recorded "main-unit"
>   Started 2023-12-12T09:55:42
>   Ended                    45
>   Total               0:00:03
> [09:55:52] ❯ timew start secondary-unit
> Note: '"secondary-unit"' is a new tag.
> Tracking "secondary-unit"
>   Started 2023-12-12T09:55:52
>   Current                  52
>   Total               0:00:00
> [09:55:55] ❯ timew stop
> Recorded "secondary-unit"
>   Started 2023-12-12T09:55:52
>   Ended                    55
>   Total               0:00:03
> [09:55:57] ❯ timew tags
> 
> Tag            Description
> main-unit      -
> secondary-unit -
> 
> [09:56:00] ❯ fish
> 
> ❯ timew start [TAB]
> main  secondary
> ```
> 
> - Shell: Fish 3.6.1
> - Timewarrior: 1.6.0 and 1.7.0

**Comment by pfmephisto** [comment]
@lauft I think this should be fixing the issue #3
